/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: fe05c25dbb0fd8911500395747af59c9)
interface __BaseEnv_CloudflareBindings {
	CACHE: KVNamespace;
	DICT: D1Database;
	APP: D1Database;
	FEED_RATE: RateLimit;
	SYNC_RATE: RateLimit;
	REC_SLOTS: 12;
	UNKNOWN_SLOTS: 6;
	WILD_SLOTS: 2;
	MIN_RATINGS: 5;
	PRIOR_STRENGTH: 5;
	SERVED_CAP: 30000;
	REC_POOL_SIZE: 3000;
	UNKNOWN_POOL_SIZE: 3000;
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REC_SLOTS" | "UNKNOWN_SLOTS" | "WILD_SLOTS" | "MIN_RATINGS" | "PRIOR_STRENGTH" | "SERVED_CAP" | "REC_POOL_SIZE" | "UNKNOWN_POOL_SIZE" | "BETTER_AUTH_SECRET">> {}
}
