/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: b99a53e06eae61036f4fd08a6f00c362)
interface __BaseEnv_CloudflareBindings {
	CACHE: KVNamespace;
	DICT: D1Database;
	APP: D1Database;
	FEED_RATE: RateLimit;
	SYNC_RATE: RateLimit;
	SESSION_RATE: RateLimit;
	APP_COMMIT: "local";
	DICT_RELEASE: "local-fixture";
	CONFIRMED_SLOTS: 6;
	PROMISING_SLOTS: 6;
	FRESH_SLOTS: 6;
	WILD_SLOTS: 2;
	MIN_RATINGS: 5;
	DISLIKE_WEIGHT: 0.25;
	CONFIRM_SCORE: 0.55;
	PARK_LOOKS: 15;
	SERVED_CAP: 30000;
	CONFIRMED_POOL_SIZE: 3000;
	PROMISING_POOL_SIZE: 3000;
	FRESH_POOL_SIZE: 3000;
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_COMMIT" | "DICT_RELEASE" | "CONFIRMED_SLOTS" | "PROMISING_SLOTS" | "FRESH_SLOTS" | "WILD_SLOTS" | "MIN_RATINGS" | "DISLIKE_WEIGHT" | "CONFIRM_SCORE" | "PARK_LOOKS" | "SERVED_CAP" | "CONFIRMED_POOL_SIZE" | "PROMISING_POOL_SIZE" | "FRESH_POOL_SIZE" | "BETTER_AUTH_SECRET">> {}
}
